apiVersion: v1
kind: Service
metadata:
  name: cust-kyc-open-web-bff-service
  labels:
    app: cust-kyc-open-web-bff-service
spec:
  selector:
    app: cust-kyc-open-web-bff-service
  ports:
  - name: 8080-tcp
    protocol: TCP
    appProtocol: http
    port: 8080
    targetPort: 8080